name: isofit_env

channels: &id1
  - https://anaconda.org/apple # Mac M1s
  - http://conda.anaconda.org/conda-forge

dependencies:
  - python>=3.8
  - pip
  - click
  - gdal>=2.0.0
  - matplotlib>=2.2.2
  - numpy>=1.20.0
  - pandas>=0.24
  - pep8>=1.7.1
  - pre-commit
  - protobuf~=3.19.0
  - pygrib
  - pytest>=3.5.1
  - pyyaml>=5.1.2
  - scikit-image>=0.17.0
  - scikit-learn>=0.19.1
  - scipy>=1.3.0
  - spectral>=0.19
  - tensorflow-deps==2.9.0 # Mac M1s
  - utm

  - pip:
    - ndsplines>=0.1.2
    - ray>=1.2.0
    - sphinx-autodoc-typehints>=1.19.4
    - xxhash>=1.2.0
    - tensorflow-macos==2.9.2 # Mac M1s
    - tensorflow-metal==0.5.1 # Mac M1s, optional but recommended
    # - tensorflow>2.0.1 # Tensorflow is provided by -macos
