# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
# Only apply to the isofit/ directory
files: ^isofit/
repos:
-   repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
    -   id: isort
        args: ["--profile", "black", "--multi-line", "3"]
-   repo: https://github.com/psf/black
    rev: stable
    hooks:
    -   id: black
