# Notes:
#   Bash shells do not use ~/.profile or ~/.bashrc so these shells need to be explicitely declared as shell: bash -el {0}
#   https://github.com/marketplace/actions/setup-miniconda#important
#
name: Example Tests

on: [push, pull_request]

jobs:
  examples:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -c "source /usr/local/bin/_activate_current_env.sh" && bash {0}
    container:
      image: jammont/isofit:latest
      env:
        ENV_NAME: test

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install Isofit
      run: |
        pip install --editable .

    # - name: Running Example - image_cube/small
    #   run: |
    #     cd examples/image_cube
    #     bash run_small.sh
    #
    # - name: Running Example - image_cube/medium
    #   run: |
    #     cd examples/image_cube
    #     bash run_medium.sh

    - name: Running Example - 20151026_SantaMonica
      run: |
        cd examples/20151026_SantaMonica
        bash run_examples.sh

    - name: Running Example - 20171108_Pasadena
      run: |
        cd examples/20171108_Pasadena
        bash run_example_modtran.sh
        python run_topoflux_example.py

    - name: Running Example - 20190806_ThermalIR
      run: |
        cd examples/20190806_ThermalIR
        python run_example_modtran_one.py
